### ISSUE TITLE
 Document all current Effects

### ISSUE THREAD

**Issue by Cfun1** [MicrosoftDocs/xamarin-communitytoolkit#106]
I am just putting this here to keep track, any one feel free to pick any of the listed missing docs effects and open a pr to document it, for maintainers feel free to edit/update this issue. 

- [ ]  IconTintColor
- [ ] [RemoveBorder](https://github.com/xamarin/XamarinCommunityToolkit/pull/492)
- [ ] [SelectAllText](https://github.com/xamarin/XamarinCommunityToolkit/pull/492)
- [ ] [Shadow](https://github.com/xamarin/XamarinCommunityToolkit/pull/725)
- [ ] Touch https://github.com/AndreiMisiukevich/TouchEffect/blob/master/README.md (not sure if up-to-date)
- [ ] VisualFeedback

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin Community Toolkit. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI Community Toolkit is the replacement for Xamarin Community Toolkit and its documentation can be found [here](https://learn.microsoft.com/dotnet/communitytoolkit/maui/).
