### ISSUE TITLE
Document all the ObjectModel classes

### ISSUE THREAD

**Issue by jfversluis** [MicrosoftDocs/xamarin-communitytoolkit#11]
Write Docs for all the ObjectModel classes that are currently available. You can find them [here](https://github.com/xamarin/XamarinCommunityToolkit/tree/main/XamarinCommunityToolkit/ObjectModel). This will also need to be added in the TOC.

- [x] AsyncCommand
- [x] AsyncValueCommand
- [ ] ObservableObject
- [ ] ObservableRangeCollection

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin Community Toolkit. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI Community Toolkit is the replacement for Xamarin Community Toolkit and its documentation can be found [here](https://learn.microsoft.com/dotnet/communitytoolkit/maui/).
