### ISSUE TITLE
[Enhancement] Add author github link

### ISSUE THREAD

**Issue by GUOLDEV** [MicrosoftDocs/xamarin-communitytoolkit#110]
It would be good if we could add the author GitHub link within the Author field in the [template](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/.template.md).
`
author: [guoldev](https://github.com/GUOLDEV)
`

**Comment by jfversluis** [comment]
Thanks for your suggestion, if you look at the published Docs, i.e. https://docs.microsoft.com/en-us/xamarin/community-toolkit/behaviors/userstoppedtypingbehavior

You can see just down from the title, here:

![image](https://user-images.githubusercontent.com/939291/113118144-78930d80-920f-11eb-8fd3-b8e41a3eac2e.png)

That this already happens based on that exact field that you are mentioning :)
