### ISSUE TITLE
Expander Header Template

### ISSUE THREAD

**Issue by bbenetskyy** [MicrosoftDocs/xamarin-communitytoolkit#118]
Hi, I really miss `HeaderTemplate` in `Expander` control.

`Expander` itself already contains `ContentTemplate` and it would be really nice to have not only `Expander.Header` but to have `Expander.HeaderTemplate` as well.

Thanks 😊

**Comment by jfversluis** [comment]
Hey @bbenetskyy I guess this is meant to be a feature request for the Toolkit? Because this is opened on the Docs repo. Could you open it on the XCT repo with the right template please? Thanks!
