### ISSUE TITLE
Document EnumToInConverter

### ISSUE THREAD

**Issue by jfversluis** [MicrosoftDocs/xamarin-communitytoolkit#121]
Merged [here](https://github.com/xamarin/XamarinCommunityToolkit/pull/1203) in XCT, needs Docs.

Asked @Hottemax if they are willing and able

**Comment by Hottemax** [comment]
> Merged [here](https://github.com/xamarin/XamarinCommunityToolkit/pull/1203) in XCT, needs Docs.
> 
> Asked @Hottemax if they are willing and able

Sure, go ahead and assign it to me

**Comment by Hottemax** [comment]
Done, can be closed

**Comment by jfversluis** [comment]
Yep! Thanks @Hottemax!
