### ISSUE TITLE
Error: Failed to create captire sesstion

### ISSUE THREAD

**Issue by andrecostanunes** [MicrosoftDocs/xamarin-communitytoolkit#122]
I get the error: "Failed to create capture session" when trying to use the front camera on the Xiaomi Redmi note 7 Android 10 device.

**Comment by jfversluis** [comment]
Thanks for reporting this! However, you opened this issue on the repo for the Docs, please open a new issue on [the repo for the actual product](https://github.com/xamarin/XamarinCommunityToolkit/issues/new/choose) using the right template. Thanks!
