### ISSUE TITLE
UTC to local string converter

### ISSUE THREAD

**Issue by LeoJHarris** [MicrosoftDocs/xamarin-communitytoolkit#133]
https://github.com/xamarin/XamarinCommunityToolkit/pull/1555

**Comment by jfversluis** [comment]
Thanks @LeoJHarris! Are you also actually going to write them? :)

**Comment by LeoJHarris** [comment]
> Thanks @LeoJHarris! Are you also actually going to write them? :)

@jfversluis yup not a problem will try to do this soon 😊

**Comment by jfversluis** [comment]
Awesome, thank you! Let me know if you need any help!

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin Community Toolkit. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI Community Toolkit is the replacement for Xamarin Community Toolkit and its documentation can be found [here](https://learn.microsoft.com/dotnet/communitytoolkit/maui/).
