### ISSUE TITLE
Live site from 'live' branch doesn't exist

### ISSUE THREAD

**Issue by VladislavAntonyuk** [MicrosoftDocs/xamarin-communitytoolkit#25]
![image](https://user-images.githubusercontent.com/33021114/97492321-0bcbcc80-196c-11eb-9400-a057dd1374f3.png)

**Comment by jfversluis** [comment]
Thanks for reporting! That is correct, we’re first trying to get a minimum amount of content for each feature before we publish the first live version. Hopefully that will be soon.

Unfortunately, the staging one is one accessible for Microsoft employees. If you need any help getting started with this, let me know :)
