### ISSUE TITLE
Final Docs check

### ISSUE THREAD

**Issue by jfversluis** [MicrosoftDocs/xamarin-communitytoolkit#31]
~All the Docs already in here or in PRs point to the old folder structure on the repo. Let's make sure everything is checked before we put this live.~

Whenever we are ready we should check:

- [x] All links to samples are added where they are available
- [x] All links are working and adhere to the new folder structure on the repo
- [ ] Check all existing code samples that they use the right namespaces or omit namespaces and use the new xmlns method
- [ ] Add to each feature the supported platforms and/or create a page that lists support for all things and the supported platforms

**Comment by jfversluis** [comment]
Seems like #48 already does a lot of the first bullet

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin Community Toolkit. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI Community Toolkit is the replacement for Xamarin Community Toolkit and its documentation can be found [here](https://learn.microsoft.com/dotnet/communitytoolkit/maui/).
