### ISSUE TITLE
Behaviors docs issues

### ISSUE THREAD

**Issue by davidbritch** [MicrosoftDocs/xamarin-communitytoolkit#34]
I've tidied up the behaviors folder. However, there are some outstanding issues:

- [ ] EmailValidationBehaviour properties/methods tables need description column filling in.
- [ ] EventToCommandBehaviour properties/methods/events tables need description column filling in.
- [ ] NumericValidationBehavior properties/methods tables need description column filling in.
- [ ] TextValidationBehavior needs syntax example, and the properties/methods/events tables need the description column filling in. Also, there aren't any sample project links.

**Comment by sthewissen** [comment]
Taking care of all of these in #7 and draft PR #36

**Comment by jfversluis** [comment]
This was also fixed as part of #36 right?

**Comment by davidbritch** [comment]
Yep.
