### ISSUE TITLE
Link not valid in emailvalidationbehavior

### ISSUE THREAD

**Issue by Cfun1** [MicrosoftDocs/xamarin-communitytoolkit#49]
Not sure which link the author have in mind in ValidationBehavior:

 https://github.com/MicrosoftDocs/xamarin-communitytoolkit/commit/7d5bc4fd4afb7726bb558619737ba18a717cbf91#diff-c8548cac4a4b9cd952fb8a6636e38ef3b10fae50cbc7b0913053a4b7a7c21e47R11

Maybe https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/7d5bc4fd4afb7726bb558619737ba18a717cbf91/docs/behaviors/textvalidationbehavior.md?  but this one is not valid.

**Comment by jfversluis** [comment]
The link will be valid once it's published. It will be processed by an engine and that will figure out what the actual path needs to be. This is so that we prevent putting hard links in there that can break. Thanks!
