### ISSUE TITLE
Details how each enum of TextDecorationFlags works

### ISSUE THREAD

**Issue by Cfun1** [MicrosoftDocs/xamarin-communitytoolkit#50]
- [textvalidationbehavior.md](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/7d5bc4fd4afb7726bb558619737ba18a717cbf91/docs/behaviors/textvalidationbehavior.md) is only describing the available options for `DecorationFlags` not even  [enumerating](https://github.com/xamarin/XamarinCommunityToolkit/blob/c57959085051784d7c4fdeefe936447186d5fdf6/src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Validators/TextDecorationFlags.shared.cs) them, without a detailed explanation on how this property works. Or maybe I am missing some obvious thing explained already in an external link of Microsoft docs? it would be nice if it will be included if it is the case.
How does `TextDecorationFlags` works? When/Why to use? how does each [Enum](https://github.com/xamarin/XamarinCommunityToolkit/blob/c57959085051784d7c4fdeefe936447186d5fdf6/src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Validators/TextDecorationFlags.shared.cs) behaves especially for [ReduceWhiteSpaces](https://github.com/xamarin/XamarinCommunityToolkit/blob/c26b86f0a0aa51069c39a5d25d9def309ff33c8e/src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Validators/TextValidationBehavior.shared.cs#L118)?

- For [emailvalidationbehavior](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/7d5bc4fd4afb7726bb558619737ba18a717cbf91/docs/behaviors/emailvalidationbehavior.md) the syntax example is shown in xaml and after that the property `DefaultRegexPattern` is mentioned, while in xaml it is `RegexPattern` instead which could be confusing.

**Comment by jfversluis** [comment]
Yep that all needs to come. Besides these Docs there will also be the API docs that will be generated from code, so we will probably point it at that once that is done. But since we're still starting this up we haven't been able to do that.

We're trying to be more complete as soon as possible. Of course if you are willing and able to figure out what these things do, you're welcome to contribute to the Docs yourself.

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin Community Toolkit. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI Community Toolkit is the replacement for Xamarin Community Toolkit and its documentation can be found [here](https://learn.microsoft.com/dotnet/communitytoolkit/maui/).
