### ISSUE TITLE
Include Screenshots of Views

### ISSUE THREAD

**Issue by Cfun1** [MicrosoftDocs/xamarin-communitytoolkit#51]
Include screenshots reflecting the resulting view after code samples/examples for each available View.

At an early stage, this will give new developers (to this package)  a preview on how a specific View (control) looks like without the need to code/build.

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin Community Toolkit. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI Community Toolkit is the replacement for Xamarin Community Toolkit and its documentation can be found [here](https://learn.microsoft.com/dotnet/communitytoolkit/maui/).
