### ISSUE TITLE
Document all current Effects

### ISSUE THREAD

**Issue by jfversluis** [MicrosoftDocs/xamarin-communitytoolkit#6]
There is currently one effect, you can find it/them [here](https://github.com/xamarin/XamarinCommunityToolkit/tree/main/XamarinCommunityToolkit/Effects)

- [ ] SafeAreaEffect

**Comment by sthewissen** [comment]
Sign me up for this one 👍

**Comment by sthewissen** [comment]
All done'd up. LGTM :)
