### ISSUE TITLE
Setup automatic merge of master to live

### ISSUE THREAD

**Issue by davidbritch** [MicrosoftDocs/xamarin-communitytoolkit#61]
Add cxwtool to the repo to automatically merge master to live, provided that a PR builds.

Why? I'm already sick of having to manually merge master to live, and I've only done it 2-3 times.

**Comment by jfversluis** [comment]
Did you do this already? Does this still needs work? :)

**Comment by davidbritch** [comment]
It's in progress.

**Comment by davidbritch** [comment]
This is now complete.
