### ISSUE TITLE
Document all current Behaviors

### ISSUE THREAD

**Issue by jfversluis** [MicrosoftDocs/xamarin-communitytoolkit#7]
Document all the Behaviors that are available today, you can find them [here](https://github.com/xamarin/XamarinCommunityToolkit/tree/main/XamarinCommunityToolkit/Behaviors)

- [ ] AnimationBehavior.shared.cs
- [x] CharactersValidationBehavior.shared.cs
- [x] EmailValidationBehavior.shared.cs
- [x] EventToCommandBehavior.shared.cs
- [ ] ImpliedOrderGridBehavior.shared.cs
- [ ] MaskedBehavior.shared.cs
- [ ] MaxLengthReachedBehavior.shared.cs
- [x] MultiValidationBehavior.shared.cs
- [x] NumericValidationBehavior.shared.cs
- [ ] RequiredStringValidationBehavior.shared.cs
- [x] TextValidationBehavior.shared.cs
- [x] UriValidationBehavior.shared.cs
- [ ] UserStoppedTypingBehavior.shared.cs
- [x] ValidationBehavior.shared.cs

~Already in progress by @AlexHedley in #5~ merged some outline in #18 but needs finishing

**Comment by jfversluis** [comment]
@sthewissen your turn

**Comment by sthewissen** [comment]
Assign me for this one and I'll see what I can whip up over the next week.

**Comment by Cfun1** [comment]
@jfversluis the link of "Here" "https://github.com/xamarin/XamarinCommunityToolkit/tree/main/XamarinCommunityToolkit/Behaviors" is not working. Some refactoring happened since that time maybe, needs to be replaced with https://github.com/xamarin/XamarinCommunityToolkit/tree/main/src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors?

**Comment by sthewissen** [comment]
Putting this here for my own administration:

- [ ] AnimationBehavior.shared.cs
- [ ] CharactersValidationBehavior.shared.cs
- [ ] EmailValidationBehavior.shared.cs
- [ ] EventToCommandBehavior.shared.cs
- [ ] ImpliedOrderGridBehavior.shared.cs
- [ ] MaskedBehavior.shared.cs
- [ ] MaxLengthReachedBehavior.shared.cs
- [ ] MultiValidationBehavior.shared.cs
- [ ] NumericValidationBehavior.shared.cs
- [ ] RequiredStringValidationBehavior.shared.cs
- [ ] TextValidationBehavior.shared.cs
- [ ] UriValidationBehavior.shared.cs
- [ ] UserStoppedTypingBehavior.shared.cs
- [ ] ValidationBehavior.shared.cs

**Comment by jfversluis** [comment]
@sthewissen also see #34

**Comment by sthewissen** [comment]
One more left to do!

**Comment by sthewissen** [comment]
All done!
