### ISSUE TITLE
Add CommandFactory Documentation

### ISSUE THREAD

**Issue by brminnick** [MicrosoftDocs/xamarin-communitytoolkit#70]
Add Documentation for Xamarin.CommunityToolkit.ObjectModel.CommandFactory

https://github.com/xamarin/XamarinCommunityToolkit/pull/797

**Comment by brminnick** [comment]
Hey @maxkoshevoi! When you get a chance, could you leave a comment on this Issue? 

Once you leave a comment, I can assign it to you.

For some reason, GitHub doesn't let us assign Issues to users until they comment on Issues 🤷‍♂️

**Comment by maxkoshevoi** [comment]
@brminnick I'll duplicate my comment from here: https://github.com/xamarin/XamarinCommunityToolkit/pull/811#issuecomment-770053027

I think this is better place for discussion that closed PR =)

### Command constructors

I understand that adding `Create` overloads that wrap parameters into some custom logic is not the best idea. But that's to unify constructors across all command types.

PR into Xamarin repo is a good idea to solve this issue. Do you think they'll accept it?

### Parameter names

Different execute parameter names are needed if user will specify more than two arguments. We don't have overloads for that.

**Comment by brminnick** [comment]
Thanks for responding, @snoopyapocalypse 

This is an issue to update the official Microsoft Docs; it is not the appropriate place for [this discussion](https://github.com/xamarin/XamarinCommunityToolkit/pull/811#issuecomment-770053027)
