### ISSUE TITLE
Document all the current Converters

### ISSUE THREAD

**Issue by jfversluis** [MicrosoftDocs/xamarin-communitytoolkit#8]
Write Docs for all the Converters that are currently available. You can find them [here](https://github.com/xamarin/XamarinCommunityToolkit/tree/main/XamarinCommunityToolkit/Converters)

- [x] BoolToObjectConverter
- [x] ByteArrayToImageSourceConverter
- [x] DateTimeOffsetConverter
- [x] DoubleToIntConverter
- [x] EqualConverter
- [x] IndexToArrayItemConverter
- [x] IntToBoolConverter
- [x] InvertedBoolConverter
- [x] IsNotNullOrEmptyConverter
- [x] IsNullOrEmptyConverter
- [x] ItemSelectedEventArgsConverter
- [x] ItemTappedEventArgsConverter
- [x] ListIsNotNullOrEmptyConverter
- [x] ListIsNullOrEmptyConverter
- [x] ListToStringConverter
- [ ] MultiConverter
- [x] NotEqualConverter
- [x] TextCaseConverter

**Comment by sthewissen** [comment]
Sign me up sir.

**Comment by sthewissen** [comment]
Redoing the list to be able to keep track of myself:

* [X]  BoolToObjectConverter
* [X]  ByteArrayToImageSourceConverter
* [ ]  DateTimeOffsetConverter
* [ ]  DoubleToIntConverter
* [ ]  EqualConverter
* [ ]  IndexToArrayItemConverter
* [ ]  IntToBoolConverter
* [ ]  InvertedBoolConverter
* [ ]  IsNotNullOrEmptyConverter
* [ ]  IsNullOrEmptyConverter
* [ ]  ItemSelectedEventArgsConverter
* [ ]  ItemTappedEventArgsConverter
* [ ]  ListIsNotNullOrEmptyConverter
* [ ]  ListIsNullOrEmptyConverter
* [ ]  ListToStringConverter
* [ ]  MultiConverter
* [ ]  NotEqualConverter
* [ ]  TextCaseConverter
