### ISSUE TITLE
Add ProgressBar Animated Progress Behavior

### ISSUE THREAD

**Issue by jfversluis** [MicrosoftDocs/xamarin-communitytoolkit#82]
This one still needs Docs: https://github.com/xamarin/XamarinCommunityToolkit/pull/352

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin Community Toolkit. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI Community Toolkit is the replacement for Xamarin Community Toolkit and its documentation can be found [here](https://learn.microsoft.com/dotnet/communitytoolkit/maui/).
