### ISSUE TITLE
Add LocalizationManager Documentation

### ISSUE THREAD

**Issue by brminnick** [MicrosoftDocs/xamarin-communitytoolkit#83]
@maxkoshevoi please add the documentation for [`LocalizationResourceManager`](https://github.com/xamarin/XamarinCommunityToolkit/blob/main/src/CommunityToolkit/Xamarin.CommunityToolkit/Helpers/LocalizationResourceManager.shared.cs)

**Comment by maxkoshevoi** [comment]
Comment so that issue can be assigned to me
