### ISSUE TITLE
Document all the current Extensions

### ISSUE THREAD

**Issue by jfversluis** [MicrosoftDocs/xamarin-communitytoolkit#9]
Write Docs for all the Extensions that are currently available. You can find them [here](https://github.com/xamarin/XamarinCommunityToolkit/tree/main/XamarinCommunityToolkit/Extensions)

- [ ] GravatarImageExtension
- [ ] ImageResourceExtension
- [ ] PageExtension
- [ ] TranslateExtension
- [ ] ValueConverterExtension

**Comment by sthewissen** [comment]
`ValueConverterExtension` probably needs no docs. It's internal/plumbing and an abstract class that all of our converters inherit from to do the magic that they do...

**Comment by sthewissen** [comment]
Sign me up for these.

**Comment by jfversluis** [comment]
Yeah whatever is internal etc. don't bother, I just looked at the files in there and put that on a list
