### ISSUE TITLE
Pre-Release 1.1.0 pre1

### ISSUE THREAD

**Issue by ryanharding** [MicrosoftDocs/xamarin-communitytoolkit#90]
Hi,

Sorry if this is the wrong place, if so please direct me to where I should log this.

In pre release 1.1.0 pre1, TouchEffect is no longer firing on UWP.

No error or warning is fired when tapping.

**Comment by jfversluis** [comment]
Hey @ryanharding !

This is indeed not the right place as this is the place to open issues for the Docs :)

Please open an issue here: https://aka.ms/xct thanks!
